name: "usage_counter"
backend: "python"
max_batch_size: 16
dynamic_batching {}
input [
  {
    name: "prompt"
    data_type: TYPE_STRING
    dims: [ -1 ]
  }
]
output [
  {
    name: "num_tokens"
    data_type: TYPE_INT32
    dims: [ -1 ]
  }
]

parameters {
  key: "tokenizer_dir"
  value: {
    string_value: "/workspace/model"
  }
}

instance_group [
    {
        count: 1
        kind: KIND_CPU
    }
]
