services:
  # Main service container
  triton:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: my-agent-in-triton:25.04
    container_name: my-agent-in-triton
    runtime: nvidia
    shm_size: 16g
    environment:
      TZ: Asia/Taipei
      NVIDIA_VISIBLE_DEVICES: 0
    volumes:
      - ../:/workspace
    working_dir: /workspace
    ports:
      - 8000:8001
    restart: unless-stopped
    command: tail -f /dev/null

  # PostgreSQL database service
  postgres:
    image: pgvector/pgvector:pg17
    environment:
      - POSTGRES_USER=postgresql
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

# Volume for data persistence
volumes:
  postgres_data:
    driver: local
