backend: "python"
max_batch_size: 1
input [
    {
        name: "input_text"
        data_type: TYPE_STRING
        dims: [ -1 ]
    },
    {
        name: "input_type"
        data_type: TYPE_STRING
        optional: true
        dims: [ -1 ]
    }
]
output [
    {
        name: "embeddings"
        data_type: TYPE_FP32
        dims: [ -1 ]
    },
    {
        name: "prompt_tokens"
        data_type: TYPE_INT32
        dims: [ 1 ]
    }
]

parameters {
  key: "model_path"
  value: {
    string_value: "/workspace/model"
  }
}

instance_group [
    {
        count: 1
        kind: KIND_CPU
    }
]
